-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "postgis";

-- CreateTable
CREATE TABLE "medidas_tdt" (
    "id" SERIAL NOT NULL,
    "id_area" BIGINT NOT NULL,
    "geom" geometry(Point, 4326) NOT NULL,
    "area_geogr" VARCHAR(100) NOT NULL,
    "provincia" VARCHAR(20) NOT NULL,
    "emisiones" VARCHAR(1) NOT NULL,
    "pto_medida" VARCHAR(3) NOT NULL,
    "n_medida" INTEGER NOT NULL,
    "fecha_hora" VARCHAR(50) NOT NULL,
    "azimut" INTEGER NOT NULL,
    "c1_servici" VARCHAR(4),
    "c1" INTEGER,
    "c1_mhz" DECIMAL(20,0),
    "nivel_c1" DECIMAL(20,2),
    "c_n_c1" DECIMAL(20,2),
    "cber_c1" DECIMAL(20,6),
    "vber_c1" DECIMAL(20,8),
    "mer_c1" DECIMAL(20,2),
    "ok_c1" VARCHAR(5),
    "c2_servici" VARCHAR(4),
    "c2" INTEGER,
    "c2_mhz" DECIMAL(20,0),
    "nivel_c2" DECIMAL(20,2),
    "c_n_c2" DECIMAL(20,2),
    "cber_c2" DECIMAL(20,6),
    "vber_c2" DECIMAL(20,8),
    "mer_c2" DECIMAL(20,2),
    "ok_c2" VARCHAR(5),
    "c3_servici" VARCHAR(4),
    "c3" INTEGER,
    "c3_mhz" DECIMAL(20,0),
    "nivel_c3" DECIMAL(20,2),
    "c_n_c3" DECIMAL(20,2),
    "cber_c3" DECIMAL(20,6),
    "vber_c3" DECIMAL(20,8),
    "mer_c3" DECIMAL(20,2),
    "ok_c3" VARCHAR(5),
    "c4_servici" VARCHAR(4),
    "c4" INTEGER,
    "c4_mhz" DECIMAL(20,0),
    "nivel_c4" DECIMAL(20,2),
    "c_n_c4" DECIMAL(20,2),
    "cber_c4" DECIMAL(20,6),
    "vber_c4" DECIMAL(20,8),
    "mer_c4" DECIMAL(20,2),
    "ok_c4" VARCHAR(5),
    "c5_servici" VARCHAR(4),
    "c5" INTEGER,
    "c5_mhz" DECIMAL(20,0),
    "nivel_c5" DECIMAL(20,2),
    "c_n_c5" DECIMAL(20,2),
    "cber_c5" DECIMAL(20,6),
    "vber_c5" DECIMAL(20,8),
    "mer_c5" DECIMAL(20,2),
    "ok_c5" VARCHAR(5),
    "c6_servici" VARCHAR(4),
    "c6" INTEGER,
    "c6_mhz" DECIMAL(20,0),
    "nivel_c6" DECIMAL(20,2),
    "c_n_c6" DECIMAL(20,2),
    "cber_c6" DECIMAL(20,6),
    "vber_c6" DECIMAL(20,8),
    "mer_c6" DECIMAL(20,2),
    "ok_c6" VARCHAR(5),
    "c7_servici" VARCHAR(4),
    "c7" INTEGER,
    "c7_mhz" DECIMAL(20,0),
    "nivel_c7" DECIMAL(20,2),
    "c_n_c7" DECIMAL(20,2),
    "cber_c7" DECIMAL(20,6),
    "vber_c7" DECIMAL(20,8),
    "mer_c7" DECIMAL(20,2),
    "ok_c7" VARCHAR(5),
    "c8_servici" VARCHAR(4),
    "c8" INTEGER,
    "c8_mhz" DECIMAL(20,0),
    "nivel_c8" DECIMAL(20,2),
    "c_n_c8" DECIMAL(20,2),
    "cber_c8" DECIMAL(20,6),
    "vber_c8" DECIMAL(20,8),
    "mer_c8" DECIMAL(20,2),
    "ok_c8" VARCHAR(5),
    "monitorizacion" VARCHAR(1),
    "obs_generales" TEXT,
    "id_formulario" VARCHAR(80) NOT NULL,
    "name" TEXT,
    "fir_nombre" VARCHAR(255),
    "fir_dni" VARCHAR(255),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "medidas_tdt_pkey" PRIMARY KEY ("id")
);
