export class MeasureEntity {
  id?: string | number;
  idArea: number;
  lat: number | null;
  lon: number | null;
  areaGeogr: string;
  provincia: string;
  emisiones: string;
  ptoMedida: string;
  nMedida: number;
  fechaHora: string;
  azimut: number;
  c1Servici: string | null;
  c1: number | null;
  c1Mhz: number | null;
  nivelC1: number | null;
  cNC1: number | null;
  cberC1: number | null;
  vberC1: number | null;
  merC1: number | null;
  okC1: string | null;
  c2Servici: string | null;
  c2: number | null;
  c2Mhz: number | null;
  nivelC2: number | null;
  cNC2: number | null;
  cberC2: number | null;
  vberC2: number | null;
  merC2: number | null;
  okC2: string | null;
  c3Servici: string | null;
  c3: number | null;
  c3Mhz: number | null;
  nivelC3: number | null;
  cNC3: number | null;
  cberC3: number | null;
  vberC3: number | null;
  merC3: number | null;
  okC3: string | null;
  c4Servici: string | null;
  c4: number | null;
  c4Mhz: number | null;
  nivelC4: number | null;
  cNC4: number | null;
  cberC4: number | null;
  vberC4: number | null;
  merC4: number | null;
  okC4: string | null;
  c5Servici: string | null;
  c5: number | null;
  c5Mhz: number | null;
  nivelC5: number | null;
  cNC5: number | null;
  cberC5: number | null;
  vberC5: number | null;
  merC5: number | null;
  okC5: string | null;
  c6Servici: string | null;
  c6: number | null;
  c6Mhz: number | null;
  nivelC6: number | null;
  cNC6: number | null;
  cberC6: number | null;
  vberC6: number | null;
  merC6: number | null;
  okC6: string | null;
  c7Servici: string | null;
  c7: number | null;
  c7Mhz: number | null;
  nivelC7: number | null;
  cNC7: number | null;
  cberC7: number | null;
  vberC7: number | null;
  merC7: number | null;
  okC7: string | null;
  c8Servici: string | null;
  c8: number | null;
  c8Mhz: number | null;
  nivelC8: number | null;
  cNC8: number | null;
  cberC8: number | null;
  vberC8: number | null;
  merC8: number | null;
  okC8: string | null;
  monitorizacion: string | null;
  obsGenerales: string | null;
  idFormulario: string | null;
  name: string | null;
  firNombre: string | null;
  firDni: string | null;
  createdAt: Date;
  updatedAt: Date;

  constructor(partial: Partial<MeasureEntity>) {
    Object.assign(this, partial);
  }

  static create(partial: Partial<MeasureEntity>): MeasureEntity {
    return new MeasureEntity(partial);
  }
}
